package com.nymbusmedia.nymbusbridge;


import com.nymbusmedia.nymbusbridge.exception.AirCableNotFoundException;


/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App implements OutputMessageListener {
    public String getGreeting() {
        return "Hello world.";
    }
    public static void main(String[] args) {

        BeaconManager beaconManager = new BeaconManager();
        try {
            beaconManager.scan();
        } catch (AirCableNotFoundException e) {
            System.out.println("AirCable not found!");
            e.printStackTrace();
        }
        System.out.println("AirCable found!");
        beaconManager.setup();
        if(!beaconManager.isOpen()) {
            beaconManager.execute(Commands.CHECK_BROADCAST_CONFIGURATION, new App());
//            beaconManager.execute(Commands.BROADCAST_WITH_100, new App());
        }
    }

    @Override
    public void onOutputMessageReceived(String message, String command) {
        System.out.print(message);
    }
}
